<a href="https://colab.research.google.com/github/gitmattalves/dados_eleitorais/blob/main/Eleicoes_2014.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importando as bibliotecas necessárias

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [ ]:
# Abrindo o arquivos de dado

df_2014 = pd.read_csv('/content/votacao_secao_2014_RR.csv', sep=';', encoding='ISO-8859-1')
df_2014.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,...,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_SECAO,CD_CARGO,DS_CARGO,NR_VOTAVEL,NM_VOTAVEL,QT_VOTOS,NR_LOCAL_VOTACAO
0,28/07/2021,11:54:26,2014,2,Eleição Ordinária,1,143,Eleições Gerais 2014,05/10/2014,F,...,3050,ALTO ALEGRE,3,12,3,Governador,13,ANGELA MARIA GOMES PORTELA,38,1015
1,28/07/2021,11:54:26,2014,2,Eleição Ordinária,1,143,Eleições Gerais 2014,05/10/2014,F,...,3050,ALTO ALEGRE,3,12,3,Governador,40,FRANCISCO DE ASSIS RODRIGUES,74,1015
2,28/07/2021,11:54:26,2014,2,Eleição Ordinária,1,143,Eleições Gerais 2014,05/10/2014,F,...,3050,ALTO ALEGRE,3,12,3,Governador,50,HAMILTON CASTRO CAVALCANTE,2,1015
3,28/07/2021,11:54:26,2014,2,Eleição Ordinária,1,143,Eleições Gerais 2014,05/10/2014,F,...,3050,ALTO ALEGRE,3,12,3,Governador,11,MARIA SUELY SILVA CAMPOS,94,1015
4,28/07/2021,11:54:26,2014,2,Eleição Ordinária,1,143,Eleições Gerais 2014,05/10/2014,F,...,3050,ALTO ALEGRE,3,12,3,Governador,95,VOTO BRANCO,2,1015

In [ ]:
type(df_2014)

pandas.core.frame.DataFrame

In [ ]:
df_2014.columns

Index(['DT_GERACAO', 'HH_GERACAO', 'ANO_ELEICAO', 'CD_TIPO_ELEICAO',
       'NM_TIPO_ELEICAO', 'NR_TURNO', 'CD_ELEICAO', 'DS_ELEICAO', 'DT_ELEICAO',
       'TP_ABRANGENCIA', 'SG_UF', 'SG_UE', 'NM_UE', 'CD_MUNICIPIO',
       'NM_MUNICIPIO', 'NR_ZONA', 'NR_SECAO', 'CD_CARGO', 'DS_CARGO',
       'NR_VOTAVEL', 'NM_VOTAVEL', 'QT_VOTOS', 'NR_LOCAL_VOTACAO'],
      dtype='object')

In [ ]:
df_2014_fltrado = df_2014[['NM_MUNICIPIO',	'NR_ZONA', 'NR_SECAO', 'DS_CARGO', 'NR_VOTAVEL','NM_VOTAVEL','QT_VOTOS']]
df_2014_fltrado

,NM_MUNICIPIO,NR_ZONA,NR_SECAO,DS_CARGO,NR_VOTAVEL,NM_VOTAVEL,QT_VOTOS
0,ALTO ALEGRE,3,12,Governador,13,ANGELA MARIA GOMES PORTELA,38
1,ALTO ALEGRE,3,12,Governador,40,FRANCISCO DE ASSIS RODRIGUES,74
2,ALTO ALEGRE,3,12,Governador,50,HAMILTON CASTRO CAVALCANTE,2
3,ALTO ALEGRE,3,12,Governador,11,MARIA SUELY SILVA CAMPOS,94
4,ALTO ALEGRE,3,12,Governador,95,VOTO BRANCO,2
...,...,...,...,...,...,...,...
152498,UIRAMUTÃ,7,81,Governador,95,VOTO BRANCO,1
152499,UIRAMUTÃ,7,81,Governador,96,VOTO NULO,17
152500,UIRAMUTÃ,7,84,Governador,40,FRANCISCO DE ASSIS RODRIGUES,40
152501,UIRAMUTÃ,7,84,Governador,11,MARIA SUELY SILVA CAMPOS,34
152502,UIRAMUTÃ,7,84,Governador,96,VOTO NULO,7

In [ ]:
dep_estadual = df_2014_fltrado[df_2014_fltrado['DS_CARGO'] == 'Deputado Estadual']
dep_estadual

,NM_MUNICIPIO,NR_ZONA,NR_SECAO,DS_CARGO,NR_VOTAVEL,NM_VOTAVEL,QT_VOTOS
55,ALTO ALEGRE,3,12,Deputado Estadual,44123,ADEJALMO MOREIRA ABADI,2
56,ALTO ALEGRE,3,12,Deputado Estadual,17123,ADELINO DIAS DE SOUSA FILHO,1
57,ALTO ALEGRE,3,12,Deputado Estadual,40147,AIRTON ANTONIO SOLIGO,6
58,ALTO ALEGRE,3,12,Deputado Estadual,43333,ALCINIRA MAGALHÃES MOTA FREITAS,5
59,ALTO ALEGRE,3,12,Deputado Estadual,43555,ALESSANDRO SILVA MAGALHÃES,1
...,...,...,...,...,...,...,...
148387,UIRAMUTÃ,7,84,Deputado Estadual,13,Partido dos Trabalhadores,4
148388,UIRAMUTÃ,7,84,Deputado Estadual,44344,RONALDO MOREIRA MATOS TRAJANO,1
148389,UIRAMUTÃ,7,84,Deputado Estadual,65600,SARA PEREIRA DA SILVA,1
148390,UIRAMUTÃ,7,84,Deputado Estadual,43123,VALDENIR FERREIRA DA SILVA,1
148391,UIRAMUTÃ,7,84,Deputado Estadual,23123,VIVIANE PEREIRA DE MORAES,4

In [ ]:
estadual_mais_votados_2014 = dep_estadual.groupby(['NM_VOTAVEL']).agg({'QT_VOTOS': 'sum'})
estadual_mais_votados_2014

                                    QT_VOTOS
NM_VOTAVEL
ADALBERTO DE ARAUJO RIBEIRO             1020
ADALNICE GAMA DA SILVA                    26
ADEJALMO MOREIRA ABADI                   559
ADELINO DIAS DE SOUSA FILHO             1230
ADI MUNIZ GOMES                          121
...                                      ...
WILLIAMS JAHNSEN FERREIRA DA SILVA        71
WILSON FRANCISCO DE MOURA                135
WILSON NUNES PEREIRA                     229
WLADIMIR CABRAL DE LIMA                   14
WYGNÉIA BARBOSA DE ALMEIDA                18

[407 rows x 1 columns]

In [ ]:
estadual_sorted = estadual_mais_votados_2014.sort_values('QT_VOTOS', ascending=False)
estadual_sorted.head(20)

                                     QT_VOTOS
NM_VOTAVEL
JALSER RENIER PADILHA                    7152
ANTONIO MECIAS PEREIRA DE JESUS          7121
FRANCISCA AURELINA DE MEDEIROS LIMA      5963
FRANCISCO JOSÉ BRITO BEZERRA             5838
FRANCISCO DE SALES GUERRA NETO           5832
MARCELO MOTA DE MACEDO                   5610
OLENO INACIO DE MATOS                    4924
MASAMY EDA                               4917
VOTO NULO                                4578
JANE JOSE DA SILVA                       4553
VALDENIR FERREIRA DA SILVA               4312
ROSINALDO ADOLFO BEZERRA DA SILVA        4094
JORGE EVERTON BARRETO GUIMARAES          4005
VOTO BRANCO                              3925
GERSON CHAGAS                            3882
ANGELA AGUIDA PORTELLA ALVES             3856
JOAQUIM DE FREITAS RUIZ                  3819
ANTONIO EDUARDO FILHO                    3778
FRANCISCO ADJAFRE DE SOUSA NETO          3741
JOSE REINALDO PEREIRA DA SILVA           3673

In [ ]:
lenir = dep_estadual[dep_estadual['NM_VOTAVEL'] == 'LENIR RODRIGUES SANTOS']
lenir

,NM_MUNICIPIO,NR_ZONA,NR_SECAO,DS_CARGO,NR_VOTAVEL,NM_VOTAVEL,QT_VOTOS
94,ALTO ALEGRE,3,12,Deputado Estadual,23456,LENIR RODRIGUES SANTOS,1
206,ALTO ALEGRE,3,13,Deputado Estadual,23456,LENIR RODRIGUES SANTOS,2
325,ALTO ALEGRE,3,14,Deputado Estadual,23456,LENIR RODRIGUES SANTOS,2
436,ALTO ALEGRE,3,15,Deputado Estadual,23456,LENIR RODRIGUES SANTOS,4
681,ALTO ALEGRE,3,17,Deputado Estadual,23456,LENIR RODRIGUES SANTOS,1
...,...,...,...,...,...,...,...
148092,UIRAMUTÃ,7,66,Deputado Estadual,23456,LENIR RODRIGUES SANTOS,3
148154,UIRAMUTÃ,7,68,Deputado Estadual,23456,LENIR RODRIGUES SANTOS,25
148238,UIRAMUTÃ,7,72,Deputado Estadual,23456,LENIR RODRIGUES SANTOS,7
148320,UIRAMUTÃ,7,81,Deputado Estadual,23456,LENIR RODRIGUES SANTOS,12
148378,UIRAMUTÃ,7,84,Deputado Estadual,23456,LENIR RODRIGUES SANTOS,5

In [ ]:
df_lenir_por_municipios = lenir.groupby(['NM_MUNICIPIO']).agg({'QT_VOTOS': 'sum'})
lenir_municipio = df_lenir_por_municipios.apply(lambda x: x.sort_values(ascending=False))
lenir_municipio

                    QT_VOTOS
NM_MUNICIPIO
BOA VISTA               1879
UIRAMUTÃ                 298
CANTÁ                    172
MUCAJAÍ                  149
NORMANDIA                147
PACARAIMA                145
ALTO ALEGRE              111
AMAJARI                   98
BONFIM                    88
CARACARAÍ                 80
CAROEBE                   43
RORAINÓPOLIS              41
SÃO LUIZ                  32
IRACEMA                   31
SÃO JOÃO DA BALIZA        23